SELECT ISNULL((
		SELECT SUM(C6_QTDVEN)
		FROM SC6010 AS SC6
		INNER JOIN SC5010 AS SC5
			ON C6_NUM = C5_NUM
				AND C5_ZZTIPO = 'V'
				AND C5_ZZRELCO = 'S'
				AND SC5.D_E_L_E_T_ <> '*'
		INNER JOIN SB1010 AS SB1
			ON B1_COD = C6_PRODUTO
				AND SB1.D_E_L_E_T_ = ''
		WHERE (
				C6_DATFAT > '+ DTOS(dUltDMes) +'
				OR C5_NOTA = ''
				)
			AND C5_EMISSAO <= '+ DTOS(dUltDMes) +'
			AND LEFT(C6_TES, 2) IN ('5A', '5B')
			AND SC6.D_E_L_E_T_ <> '*'
			AND B1_ZZSUBGR = 'AM'
			AND B1_ZZMARCA <> '25'
			AND B1_ZZGRIFE BETWEEN '0001' AND '9999'
		), 0) AS [CART_ANTERIOR]
		,ISNULL((
		SELECT SUM(C6_QTDVEN)
		FROM SC6010 AS SC6
		INNER JOIN SB1010 AS SB1
			ON B1_COD = C6_PRODUTO
				AND SB1.D_E_L_E_T_ = ''
		INNER JOIN SC5010 AS SC5
			ON C6_NUM = C5_NUM
				AND SC5.D_E_L_E_T_ = ''
				AND C5_ZZTIPO = 'V'
				AND C5_ZZRELCO = 'S'
				AND SC5.D_E_L_E_T_ <> '*'
		WHERE SC6.D_E_L_E_T_ = ''
			AND (
				C6_DATFAT > '+ DTOS(dUltDMes) +'
				OR C5_NOTA = ''
				)
			AND C5_EMISSAO <= '+ DTOS(dUltDMes) +'
			AND LEFT(C6_TES, 2) IN ('5D')
			AND SC6.D_E_L_E_T_ <> '*'
			AND B1_ZZSUBGR = 'AM'
			AND B1_ZZMARCA <> '25'
			AND B1_ZZGRIFE BETWEEN '0001' AND '9999'
		), 0) AS [CAR_ANT_ME]
		,ISNULL((
		SELECT SUM(D3_QUANT) - SUM(H6_ZZQTDMI)
		FROM SD3010 AS SD3
		INNER JOIN SB1010 AS SB1
			ON B1_COD = D3_COD
				AND SB1.D_E_L_E_T_ = ''
		INNER JOIN SC2010 AS SC2
			ON C2_NUM + C2_ITEM + C2_SEQUEN = D3_OP
		LEFT JOIN SH6010 AS SH6
			ON D3_IDENT = H6_IDENT
				AND SH6.D_E_L_E_T_ <> '*'
		WHERE SD3.D_E_L_E_T_ = ''
			AND D3_EMISSAO BETWEEN '+ DTOS(dPriDMes) +' AND '+ DTOS(dUltDMes) +'
			AND D3_CF = 'PR0'
			AND B1_ZZSUBGR = 'AM'
			AND D3_ESTORNO <> 'S'
			AND B1_ZZMARCA <> '25'
			AND B1_ZZGRIFE BETWEEN '0001' AND '9999'
			AND C2_ZZPEDC5 = ''
		), 0) AS PRODUCAO
		,ISNULL((
		SELECT SUM(H6_ZZQTDMI)
		FROM SD3010 AS SD3
		INNER JOIN SB1010 AS SB1
			ON B1_COD = D3_COD
				AND SB1.D_E_L_E_T_ <> '*'
		LEFT JOIN SH6010 AS SH6
			ON D3_IDENT = H6_IDENT
				AND SH6.D_E_L_E_T_ <> '*'
		WHERE D3_TIPO = 'PA'
			AND B1_ZZGRIFE BETWEEN '0001' AND '9999'
			AND B1_DESC NOT LIKE '%ESTOJO%'
			AND D3_EMISSAO BETWEEN '+ DTOS(dPriDMes) +' AND '+ DTOS(dUltDMes) +'
			AND D3_CF = 'PR0'
			AND D3_ESTORNO <> 'S'
			AND SD3.D_E_L_E_T_ <> '*'
			AND B1_ZZMARCA <> '25'
		), 0) AS PRODUCAO_MI
		,ISNULL((
		SELECT SUM(D3_QUANT)
		FROM SD3010 AS SD3
		INNER JOIN SB1010 AS SB1
			ON B1_COD = D3_COD
				AND SB1.D_E_L_E_T_ <> '*'
		WHERE D3_TIPO = 'PA'
			AND B1_ZZGRIFE BETWEEN '0001' AND '9999'
			AND B1_DESC NOT LIKE '%ESTOJO%'
			AND D3_EMISSAO BETWEEN '+ DTOS(dPriDMes) +' AND '+ DTOS(dUltDMes) +'
			AND D3_CF = 'PR0'
			AND D3_ESTORNO <> 'S'
			AND SD3.D_E_L_E_T_ <> '*'
			AND B1_ZZMARCA = '25'
		), 0) AS SOLAR
		,ISNULL((
		SELECT SUM(D3_QUANT)
		FROM SD3010 AS SD3
		INNER JOIN SB1010 AS SB1
			ON B1_COD = D3_COD
				AND SB1.D_E_L_E_T_ <> '*'
		WHERE D3_TIPO = 'PA'
			AND B1_ZZGRIFE = 'EST'
			--AND B1_DESC LIKE '%ESTOJO%'
			AND D3_EMISSAO BETWEEN '+ DTOS(dPriDMes) +' AND '+ DTOS(dUltDMes) +'
			AND D3_CF = 'PR0'
			AND D3_ESTORNO <> 'S'
			AND SD3.D_E_L_E_T_ <> '*'
		), 0) AS ESTOJO
		,ISNULL((
		SELECT SUM(D3_QUANT)
		FROM SD3010 AS SD3
		INNER JOIN SB1010 AS SB1
			ON B1_COD = D3_COD
				AND SB1.D_E_L_E_T_ <> '*'
		WHERE D3_TIPO = 'PA'
			AND B1_ZZGRIFE = 'CHV'
			AND B1_DESC LIKE '%MINIATURA%'
			AND D3_EMISSAO BETWEEN '+ DTOS(dPriDMes) +' AND '+ DTOS(dUltDMes) +'
			AND D3_CF = 'PR0'
			AND D3_ESTORNO <> 'S'
			AND SD3.D_E_L_E_T_ <> '*'
		), 0) AS MINIATURAS
		,ISNULL((
		SELECT SUM(C6_QTDVEN)
		FROM SC6010 AS SC6
		INNER JOIN SC5010 AS SC5
			ON C5_NUM = C6_NUM
				AND SC5.D_E_L_E_T_ <> '*'
		INNER JOIN SB1010 AS SB1
			ON B1_COD = C6_PRODUTO
				AND SB1.D_E_L_E_T_ <> '*'
		WHERE C5_ZZRELCO = 'S'
			AND C5_ZZDTREL BETWEEN '+ DTOS(dPriDMes) +' AND '+ DTOS(dUltDMes) +'
			AND LEFT(C6_TES, 2) IN ('5A', '5B')
			AND SC6.D_E_L_E_T_ <> '*'
		--	AND SC5.C5_TIPO = 'N'
			--AND SC5.C5_ZZTIPO = 'V'
		--				AND C6_ZZMETA = 'S'												
		), 0) AS [VENDIDAS]
		,ISNULL((
		SELECT SUM(C6_QTDVEN)
		FROM SC6010 AS SC6
		INNER JOIN SC5010 AS SC5
			ON C5_NUM = C6_NUM
				AND SC5.D_E_L_E_T_ <> '*'
		INNER JOIN SB1010 AS SB1
			ON B1_COD = C6_PRODUTO
				AND SB1.D_E_L_E_T_ <> '*'
		WHERE C5_ZZRELCO = 'S'
			AND C5_ZZDTREL BETWEEN '+ DTOS(dPriDMes) +' AND '+ DTOS(dUltDMes) +'
			AND LEFT(C6_TES, 2) IN ('5D')
			AND SC6.D_E_L_E_T_ <> '*'
			AND B1_ZZSUBGR = 'AM'
			AND B1_ZZMARCA <> '25'
			AND B1_ZZGRIFE BETWEEN '0001' AND '9999'
		), 0) AS [VENDIDAS_ME]
		,ISNULL((
		SELECT SUM(D2_QUANT)
		FROM +RetSqlName(SD2)+ SD2
		INNER JOIN SB1010 AS SB1
			ON B1_COD = D2_COD
				AND B1_ZZGRIFE BETWEEN '0001' AND '9999'
				AND SB1.D_E_L_E_T_ <> '*'
		WHERE D2_EMISSAO BETWEEN '+ DTOS(dPriDMes) +' AND '+ DTOS(dUltDMes) +'
			AND LEFT(D2_TES, 2) IN ('5A', '5B')
			AND SD2.D_E_L_E_T_ <> '*'
		), 0) AS [FATURADAS]
		,ISNULL((
		SELECT SUM(D2_QUANT)
		FROM +RetSqlName(SD2)+ SD2
		INNER JOIN SB1010 AS SB1
			ON B1_COD = D2_COD
				AND B1_ZZGRIFE BETWEEN '0001' AND '9999'
				AND SB1.D_E_L_E_T_ <> '*'
		WHERE D2_EMISSAO BETWEEN '+ DTOS(dPriDMes) +' AND '+ DTOS(dUltDMes) +'
			AND LEFT(D2_TES, 2) IN ('5D')
			AND SD2.D_E_L_E_T_ <> '*'
					AND B1_ZZSUBGR = 'AM'
			AND B1_ZZMARCA <> '25'
			AND B1_ZZGRIFE BETWEEN '0001' AND '9999'
		), 0) AS [FATURADAS_ME]